import { Hono } from 'hono';
import { cors } from 'hono/cors';
import { HTTPException } from 'hono/http-exception';
import { experiences } from './routes/experiences.js';
import { scans } from './routes/scans.js';

/**
 * @type {Hono<{ Bindings: Env }>}
 * `Env` comes from worker-configuration.d.ts, regenerated by `wrangler types`
 * whenever wrangler.jsonc changes. Without it `c.env` is untyped and every
 * binding access is a guess.
 */
const app = new Hono();

/**
 * The app is deployed separately from this Worker, so every browser call is
 * cross-origin. `CORS_ORIGIN` is a comma-separated allow-list, or "*".
 */
app.use('*', (c, next) =>
  cors({
    origin: c.env.CORS_ORIGIN === '*' ? '*' : c.env.CORS_ORIGIN.split(',').map((o) => o.trim()),
    allowMethods: ['GET', 'HEAD', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
    allowHeaders: ['content-type'],
    // The scan beacon and the target download are both read by the client.
    exposeHeaders: ['content-length'],
    maxAge: 86_400,
  })(c, next),
);

app.use('*', async (c, next) => {
  await next();
  c.header('X-Content-Type-Options', 'nosniff');
  c.header('Referrer-Policy', 'same-origin');
});

app.get('/healthz', (c) => c.json({ ok: true }));

app.route('/api/experiences', experiences);
app.route('/api/scans', scans);

app.notFound((c) => c.json({ error: 'Not found' }, 404));

app.onError((err, c) => {
  // Errors raised by badRequest/notFound carry their own JSON response.
  if (err instanceof HTTPException) return err.getResponse();
  console.error(err);
  return c.json({ error: err.message ?? 'Internal error' }, 500);
});

export default app;
